### ISSUE TITLE
Options for category, etc?

### ISSUE THREAD

**Issue by kraftbj** [MichaelArestad/Press-This#12]
In https://core.trac.wordpress.org/ticket/29298 , there's a mention that this plugin lacks the ability to choose a category for a post where the current version allows it.

**Comment by MichaelArestad** [comment]
There were two ideas for this. One was to put the categories/tags/whatever into a settings panel visible on the top right. The second was to do it after clicking a next/publish button. 

Super rough:

![image](https://cloud.githubusercontent.com/assets/1123119/5848369/c3e78418-a194-11e4-8821-cb14de88a36f.png)

**Comment by MichaelArestad** [comment]
> Maybe categories and tags are common actions enough to be on the initial screen.

I'm still leaning toward them being off screen until settings icon is clicked. (then slide in)

**Comment by StaggerLeee** [comment]
Maybe both solutions are equal right. But put some info so we know Categories options wait on next screen. I am not unexperienced with WP and i tought post will be as standard added to "Uncategorized" category.

**Comment by melchoyce** [comment]
I like how the apps handle meta information, which is pretty much in line with putting the options inside the "settings" tab: 

https://cloudup.com/cUtWeTFknWE

The only issue being, of course, discoverability — when they're hidden, they're easy to forget about, or not find at all. I find having a screen in between drafting and publishing to be pretty disruptive, however, so I'm leaning in the direction of putting them in settings. (Though I think if we do that, we need to have a broader discussion around whether the settings screen is post settings, or Press This settings.)

I'm also totally okay with the idea of excluding meta for 4.2 and using @stephdau's method of going to wp-admin upon draft.

**Comment by MichaelArestad** [comment]
I'm going to push this back to Future release until we get more of the core components finished.

**Comment by stephdau** [comment]
Being developed in #45.
