### ISSUE TITLE
Can we automatically push to the repo daily?

### ISSUE THREAD

**Issue by MichaelArestad** [MichaelArestad/Press-This#19]
This was something @ryanboren suggested and I think we should set this up immediately if possible.

**Comment by georgestephanis** [comment]
We'd probably need a box for it to live on, that would have .org password credentials hardcoded.  Maybe if there was a push bot account created?

**Comment by danielbachhuber** [comment]
> We'd probably need a box for it to live on

You can actually have Travis perform this task for you, and encrypt the password credentials in your `.travis.yml`

**Comment by georgestephanis** [comment]
I'm hesitant to trust storing an encrypted password publicly ... or is it just an identifier for a password stored on travis servers or something?

**Comment by danielbachhuber** [comment]
If you don't trust encryption, you probably shouldn't trust SSL, etc.

WP-CLI uses this to push builds:
* Encryption: https://github.com/wp-cli/wp-cli/blob/master/.travis.yml#L13
* Deployment script: https://github.com/wp-cli/wp-cli/blob/master/ci/deploy.sh

I think @dd32 had some script in progress that you could build form.

**Comment by dd32** [comment]
I'm currently working on some tooling for feature plugins, and should be able to have it syncing to w.org very soon without plugins needing to handle all this stuff themselves.

**Comment by stephdau** [comment]
Just a note that pushing from GH to the w.org repo had so far been achieved using https://github.com/MichaelArestad/Press-This/blob/master/tools/git2svn.sh, if any of it can still be useful.

**Comment by MichaelArestad** [comment]
@dd32 got this up and running. It updates the version nightly and sends each commit to the plugin repo instantly.

**Comment by stephdau** [comment]
W00t!
