### ISSUE TITLE
Dragon drop

### ISSUE THREAD

**Issue by MichaelArestad** [MichaelArestad/Press-This#23]
Would love the ability for drag and drop media/whatever.

**Comment by georgestephanis** [comment]
Drag and drop from where to where?  I don't think from the desktop makes sense (apart from what the wp native wysiwyg already natively supports) -- are you thinking an 'asset drawer' for things found in the origin post, that could be dropped to the editor?

**Comment by MichaelArestad** [comment]
This would be more used if you're using PT as an editor (without pressing anything). If the native WYSIWYG already supports it, heck yeah!

**Comment by stephdau** [comment]
We should gain that once we implement tinymce (in teeny mode: http://wpfilte.rs/teeny_mce_buttons/) and the standard media library, right?

**Comment by MichaelArestad** [comment]
We have dragon drop. Props @azaozz

**Comment by georgestephanis** [comment]
![trogdor](https://cloud.githubusercontent.com/assets/941023/5992396/03b4f418-a9f6-11e4-8b70-f7bc5dacfeb0.png)
