### ISSUE TITLE
Feature requests: Pre-linked text and link target

### ISSUE THREAD

**Issue by Tom-Usher** [MichaelArestad/Press-This#25]
I use Press This. Every time it's updated, I manually change the code so that rather than saying "via" concerning the linked post, it says "Source: ." I also make the resulting link open in a new browser tab via  target="_blank".

May I suggest that the beginning text be able to be changed via an option (text box) and that users be able to select how to handle links: self, top, blank, parent....

I would make them default settings with the ability of the user to override his or her default on a post-by-post basis.

Thanks.

That's all I have for now.

**Comment by MichaelArestad** [comment]
> I also make the resulting link open in a new browser tab via target="_blank".

We did add link controls now, so you can definitely change this. (though you still have to do it every time)

We're not adding much in the way of settings for 4.2. We'll keep this in mind when we get into more advanced features.

**Comment by stephdau** [comment]
I've added 2 filters in 0e8122d:
 * `press_this_source_string`, which allows you to change the "Source:" value.
 * `press_this_source_link`, which allows you to change the `<a>` tag surrounding the source attribution.

Note: don't consider this as what will be in the "final version" yet. Leaving it as this, for now, and we'll see about more extensibility once/if we get to be merged into core. :)

**Comment by stephdau** [comment]
Examples:
```
<?php
add_action( 'init', 'my_init' );

function my_init() {
	add_filter( 'press_this_source_string', 'pt_src_str' );
	add_filter( 'press_this_source_link', 'pt_src_lnk' );
}

function pt_src_str( $string ) {
	return 'Via:';
}

function pt_src_lnk( $string ) {
	return '<a href="%1$s" target="_blank">%2$s</a>';
}
```
