### ISSUE TITLE
Can't Press a Google result page

### ISSUE THREAD

**Issue by marcelomazza** [MichaelArestad/Press-This#29]
I'm not being able to Press a result page of Google (the homepage works fine). I'm getting a JS error when clicking in the bookmarklet.

### Example URL
https://www.google.com/?gfe_rd=cr&ei=p3XFVPL0JM2DbMH3gbAE&gws_rd=ssl,cr&fg=1#safe=off&q=wordpress

### Console
Uncaught TypeError: undefined is not a function
WpPressThis_Bookmarklet
(anonymous function)

### Specs
Google Chrome Version 40.0.2214.91 (64-bit)
Ubuntu 14.10

**Comment by stephdau** [comment]
Interesting… I wonder what kind of black magic Google is employing there. :)=

**Comment by kem226** [comment]
I found that the JS error is also thrown on this page:http://canvasengine.net and all pages on that site.  Not sure what it has in common with the google search pages.

**Comment by stephdau** [comment]
And now, same on Twitter and TechCrunch (in Chrome). I first suspected that it was due to some content policy headers, but I no longer think it's the case.

The error I get in each case is:
```
Uncaught TypeError: undefined is not a function
 WpPressThis_Bookmarklet
  (anonymous function)
```



Gotta test in other browsers, and see what's up.

**Comment by stephdau** [comment]
See 26b182b998b87ced721e0f74c4ba12a007ae11f8 – it seems to be an issue with `querySelectorAll()`. Stopped using it for now, non-critical processing.
