### ISSUE TITLE
"Upgrade your bookmarklet" improvements

### ISSUE THREAD

**Issue by marcelomazza** [MichaelArestad/Press-This#31]
This is the message you get when you install the new Press This plugin but you had the old bookmarklet on your Bookmarks Bar:

![welcome to press this - google chrome_034](https://cloud.githubusercontent.com/assets/384622/5893861/8e97d62e-a4f4-11e4-9bfe-0a718377e551.jpg)

If you click on "your bookmarklet" you go to the "Tools" page of Admin...

**maybe it's better to append the bookmarklet in the message, to be able to dragndrop it directly to the bookmarks bar / righ click it?**

Rough mockup:
![upgrade-bookmarklet_r1_c1](https://cloud.githubusercontent.com/assets/384622/5893943/31da1e30-a4f7-11e4-91d6-680384be3e32.jpg)

**Comment by MichaelArestad** [comment]
CC @stephdau

**Comment by MichaelArestad** [comment]
That would be super slick if we can do it. Possible @stephdau ?

**Comment by stephdau** [comment]
Possible: most definitely!
Desirable: not entirely sure: would it require some help text to go along with it, therefore (at least temporarily) cluttering the screen? Maybe we could make it dismissible, until the next version.

**Comment by marcelomazza** [comment]
@stephdau I did a fast mockup, the height wouldn't need to change:

![upgrade-bookmarklet_r1_c1](https://cloud.githubusercontent.com/assets/384622/5893943/31da1e30-a4f7-11e4-91d6-680384be3e32.jpg)

(was on the other comment but maybe got lost!)

**Comment by stephdau** [comment]
I like that a lot!

**Comment by marcelomazza** [comment]
Also: we need to make sure that the link now redirects to the new PT option page:

![image](https://cloud.githubusercontent.com/assets/384622/6176959/25a12234-b303-11e4-9f83-83e9163050a9.png)

Right now is still pointing to `wp-admin/tools.php`.

**Comment by marcelomazza** [comment]
I'm on commit d1193830d60d54fd3e66b44f60adca2baf55a9d7 and there is no link showing up:
![image](https://cloud.githubusercontent.com/assets/384622/6311301/fe94d672-b960-11e4-9e60-f9fb71220785.png)
I tried to mess around with the code to see if I could bring it back but I couldn't. :(

**Comment by stephdau** [comment]
no link: It does now.
