### ISSUE TITLE
n00b questions

### ISSUE THREAD

**Issue by danielbachhuber** [MichaelArestad/Press-This#35]
I tried pressing a link and got this:

![image](https://cloud.githubusercontent.com/assets/36432/5930447/9bbebc18-a644-11e4-94db-2357c5cf69c2.png)

I like my asides to end up like this:

![image](https://cloud.githubusercontent.com/assets/36432/5930452/ac168e42-a644-11e4-92b7-672d06c4899a.png)

How should I get from point A to point B?

**Comment by MichaelArestad** [comment]
Good question. I suspect that when we add more functionality to the editor, removing styles and appending content will be quite a bit nicer.

Im your case there is no pleasant way to get to point B. You would need to remove the image (easy) and hit the Save Draft button.  Then, use the full editor to modify styles (kinda lame).

**Comment by danielbachhuber** [comment]
> You would need to remove the image (easy) and hit the Save Draft button. Then, use the full editor to modify styles (kinda lame).

Ok. This is what I did for now. Looking forward to following along on the project :)

```
*/15 * * * * cd /home/dbachhuber/webapps/dbcom/wp-content/plugins/press-this; git pull origin master; > /dev/null 2>&1
```

**Comment by stephdau** [comment]
Just a note that the image, in that case, is part of the implicit [Gr]avatar support we said we'll [likely remove](https://github.com/MichaelArestad/Press-This/issues/36#issuecomment-71896654).
