### ISSUE TITLE
Dashicons and TinyMCE

### ISSUE THREAD

**Issue by MichaelArestad** [MichaelArestad/Press-This#37]
It looks like at first glance that Dashicons (both font and stylesheet) are bundled with the TinyMCE editor. Is there any way we can change that? I'd love tor replace the icons with SVG icons.

CC @azaozz @stephdau

**Comment by stephdau** [comment]
For the record: related convo: https://wordpress.slack.com/archives/feature-pressthis/p1422635599000495=
