### ISSUE TITLE
Discover HTTPS on external site assets

### ISSUE THREAD

**Issue by jeremyfelt** [MichaelArestad/Press-This#41]
I'm not sure how feasible this is, but its something I noticed the other day when using Press This.
- If my site is HTTPS and the bookmarklet opens an HTTPS window.
- And the site I'm blogging is HTTP.
- The images discovered for possible side-loading all throw mixed content errors in the browser.

It would be extra cool if we could determine that a site (e.g. http://newyorker.com) also supports HTTPS and switch the scheme when creating the post.

It may also be too much overhead to attempt HEAD requests in the background, not sure.

**Comment by stephdau** [comment]
We try to default to https whenever we know for sure we can, but the HEAD calls you suggest could be added upon image sideloading.

Ideally, that would be done in core's `media_sideload_image ()` ([ref](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/media.php#L830)), but we ca also [do it ourselves in the related method](https://github.com/MichaelArestad/Press-This/blob/master/press-this.php#L374). Note that the latter currently needs to be updated to work with the images being appended to TinyMCE, which will make it closer to what [core's PT has been doing](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/press-this.php#L46), and so long as we keep said sideloading (see #42).
