### ISSUE TITLE
Double line caused by featured image container

### ISSUE THREAD

**Issue by marcelomazza** [MichaelArestad/Press-This#43]
![image](https://cloud.githubusercontent.com/assets/384622/6097556/c99a398c-afc2-11e4-9cd5-e6b999e69feb.png)

![image](https://cloud.githubusercontent.com/assets/384622/6097554/c11fc2cc-afc2-11e4-9c1f-9730bbabb6b8.png)

**Comment by MichaelArestad** [comment]
Looks like the `.no-media` class is no longer being applied.

![image](https://cloud.githubusercontent.com/assets/1123119/6097619/09df08ec-af82-11e4-8cdf-339d2b5a86ec.png)

CC @azaozz @stephdau

**Comment by stephdau** [comment]
OK, will fix next time I'm at a keyboard.

**Comment by stephdau** [comment]
Fixed in a6cef3b.
