### ISSUE TITLE
No URL: Placeholders for New Post and textarea

### ISSUE THREAD

**Issue by marcelomazza** [MichaelArestad/Press-This#44]
When you invoke PT from a URL the title and the content are scrapped and shown in the PT window, which is cool, because you don't need to type anything.

When you invoke PT from an empty tab/direct link, you get the PT screen saying:

  "New Post"
  "Start typing here."

If I tap on any of those two, I need to delete delete delete all the content to start typing. A possible improvement would be to convert those two in placeholders.

If this is not possible, an alternative could be to "select all" the content on focus, so with a single backspace/delete you remove everything (or you can even start typing if you want).

**Comment by stephdau** [comment]
@marcelomazza, @MichaelArestad: Are placeholders okay with our accessibility standards?

I see TinyMCE seems to [support placeholders](http://www.tinymce.com/wiki.php/api4:setting.tinymce.ui.ComboBox.placeholder). @azaozz: what's you experience with that?

**Comment by azaozz** [comment]
@stephdau in TinyMCE that placeholder is for the popups/dialogs. They are all created from JS, so this is the way to add a placeholrer in there.

**Comment by MichaelArestad** [comment]
@stephdau Placeholders are pretty good as long as the form field has an actual label. Also, I noted we're using an H2 for the header still which does not support placeholders. If we want placeholders there, we should switch to an input.

**Comment by marcelomazza** [comment]
Just as a reference, this was mentioned in [Press This: Accessibility user test result](https://make.wordpress.org/accessibility/2015/02/09/press-this-accessibility-user-test-result/):
> When the user tabs to the area to add the title of the post or to enter text, they have to highlight and delete the text or backspace to remove it so it is not added to the text they are typing.

**Comment by azaozz** [comment]
I'm not so sure we need a placeholder for the editor. Before we used TinyMCE it was a bit vague where post_content "begins". Now it is quite obvious it is under the buttons :)

Probably can use a textarea for the title. Text field wouldn't wrap.

**Comment by kraftbj** [comment]
Using h2 breaks HTML validation if we're using a label element. See #57, item 9.

**Comment by marcelomazza** [comment]
I will replace the `label` element and will use the attribute `aria-labelledby` in the `h2` instead.

I forgot to reference here this commit were I put back the `h2`:
https://github.com/MichaelArestad/Press-This/commit/04dc1fdec26884424c42d5c44eba017a8ba11446

**Comment by marcelomazza** [comment]
Changed `label` to `span` https://github.com/MichaelArestad/Press-This/pull/59

**Comment by marcelomazza** [comment]
So, the "placeholder" for the Title is ready and done. We need to discuss what to do with the "placeholder" of TinyMCE. I talked about it with azaozz in Slack ([see chat](https://wordpress.slack.com/archives/feature-pressthis/p1423774524003932)) and the alternatives are:

 - We can remove the "Start typing here" altogether. Assumption: is pretty obvious were to type.
 - If we want to add a proper placeholder we need to add another element under the iframe and do magic

What do you think?

**Comment by MichaelArestad** [comment]
Removing it could be a bit too mysterious (though it would look good). Let's test it.
