### ISSUE TITLE
Typo in Admin Notice "Preferred misspelled" Line 939 of press-this.php

### ISSUE THREAD

**Issue by chazzzzy** [MichaelArestad/Press-This#46]
Hope I am not out of place coming in here, but I noticed a typo on the Admin notice that everyone sees when they install the plugin.

Line 939 "preferred" is misspelled.  It says "and select your preffered install method"

Charles

**Comment by stephdau** [comment]
Thanks. That’s my bad. Fixed in 318456e. :)
It’s just a temporary notice until we come up what the text will actually be, and how/if we’ll prompt users about it.
