### ISSUE TITLE
Jetpack error (grunion/contact form)

### ISSUE THREAD

**Issue by MichaelArestad** [MichaelArestad/Press-This#51]
@ryanboren found this error this morning after updating from the repo. I have not been able to reproduce.

![image](https://cloud.githubusercontent.com/assets/1123119/6149178/1c710412-b1c4-11e4-8743-af573d52a628.png)

@azaozz ideas?

**Comment by georgestephanis** [comment]
https://github.com/Automattic/jetpack/blob/master/modules/contact-form/admin.php#L43

Looks like the `$current_screen` global either isn't set, or isn't an object.

Feels odd.  Did we change the order of processing lately so `admin_print_styles` may be running before current screen is set?

**Comment by kraftbj** [comment]
`git bisect` determined 63e6df243b9c66a80d95467056904b58f514cc91 to be the first commit to generate this issue.

**Comment by MichaelArestad** [comment]
Yeah. Probably this: https://github.com/MichaelArestad/Press-This/commit/63e6df243b9c66a80d95467056904b58f514cc91#diff-c7f2f9aa9d5a73f0567bf71b0b6d1672R825

**Comment by kraftbj** [comment]
Working an idea... PT is loaded via the `admin_init` hook for the press-this.php override, which occurs at https://github.com/WordPress/WordPress/blob/master/wp-admin/admin.php#L158

`set_current_screen();` doesn't occur for another 30 or so lines at https://github.com/WordPress/WordPress/blob/master/wp-admin/admin.php#L191

I think we can fix this simply by adding `set_current_screen()` within `serve_app_html()`

**Comment by stephdau** [comment]
Applied @kraftbj's logic (though not your commit per se). Solid enough, since only an issue while a plugin.

**Comment by kraftbj** [comment]
Close enough for me :)
