### ISSUE TITLE
Need a better default embed icon in the list when no preview.

### ISSUE THREAD

**Issue by stephdau** [MichaelArestad/Press-This#55]
See https://cloudup.com/iSNWnRT1uEk

We can only get a thumb preview for embeds for Youtube at the moment, when listing the ones available. So, Vimeo, twitter, etc embeds are shown in the list as a grey square, with the tell-tale play icon superimposed.

Could we make that square use the same icon as while the wpViews are still getting their own previews, once embedded in the editor?
![screen shot 2015-02-12 at 11 38 09](https://cloud.githubusercontent.com/assets/1891/6171906/b5cc2ec4-b2ab-11e4-8300-1a702fdabf55.png)

 Maybe another color? I'd keep the same play triangle, for consistency.
I'll leave that up to your designy attentions. :)

**Comment by MichaelArestad** [comment]
Would it be a PITA to add a class describing the type of embed (when possible) so I can add an icon/design that pertains to that embed with a generic fallback as seen above?

**Comment by MichaelArestad** [comment]
@stephdau ^

**Comment by MichaelArestad** [comment]
Added icons. Boom. 8)
