### ISSUE TITLE
Landing location after saving a draft

### ISSUE THREAD

**Issue by kraftbj** [MichaelArestad/Press-This#56]
When clicking Save Draft in PT, currently, the full wp-admin for the post is loaded in the parent window.

This behavior moves you away from the source page and, if you wish to return to the source for reference or to continue navigating through that site, you have to use browser buttons to back into it.

Suggestion: Open a new tab upon saving a draft to full wp-admin, not loading it in parent.opener.

@ryanboren @azaozz @MichaelArestad 

Slack chat: https://wordpress.slack.com/archives/feature-pressthis/p1423758985003773

**Comment by ryanboren** [comment]
https://make.wordpress.org/flow/2015/02/12/press-this-continue-in-full-editor-macnchrome-4-2-alpha-31427-pt-0-0-6-20150212/

**Comment by MichaelArestad** [comment]
> Suggestion: Open a new tab upon saving a draft to full wp-admin, not loading it in parent.opener.

Makes sense if it's feasible.

**Comment by azaozz** [comment]
Not sure we can both open a new tab next to the parent one and redirect to it. Actually it is pretty hard to open any mew window (popup or tab) from JS as all browsers block "popups" by default, and there are tons of security "things" that block them even more :)

As far as I see the only way `window.open()` would work is if it's inline JS, and even then some anti-malware apps may block it.

Need to test a bit more but for now it seems in JS we can only redirect to the parent. If a form is posted we can do `target="_blank"` but that would open another tab in the popup, not the parent.

**Comment by azaozz** [comment]
Another idea: after clicking Save Draft or Publish, we open an overlay with a spinner (or something else that means "waiting"). Then when we get the ajax response we show two buttons:
- Close (and continue browsing).
- View or Edit post.

Currently PT just waits for the response and "nothing happens". If the server/internet connection is slow(er), it looks like something may be wrong.

**Comment by stephdau** [comment]
That could be interesting too, despite the options-not-decisions feel to it.

**Comment by marcelomazza** [comment]
Summary of what we talked today: https://wordpress.slack.com/archives/feature-pressthis/p1424369404006368

Press This will always live in it's popup:

 - If you hit Save Draft -> you will end up in wp-admin, editing the post (inside the popup)
 - If you hit Publish -> you will end up in the post permalink (inside the popup)

We need to make sure that there's proper feedback when you click on Save Draft or Publish (spinners, loading animation, etc).

**Comment by stephdau** [comment]
Is this the final word on this, @azaozz ? Before we start implementing it.
