### ISSUE TITLE
Text formatting on blank tab.

### ISSUE THREAD

**Issue by MichaelArestad** [MichaelArestad/Press-This#6]
Right now, "Start typing here" is in an empty div. I tried mucking around with adding it in a `p` tag, but on selecting it, the tag is stripped away. This leads to that goofy spacing between the text and the title element.

![image](https://cloud.githubusercontent.com/assets/1123119/4067160/36142880-2e2b-11e4-8721-e48dcbb9b112.png)

**Comment by marcelomazza** [comment]
Hello! I submitted a PR for this one, I'm not sure if I'm following the correct GitHub workflow so if anything can be improved, please let me know!

https://github.com/MichaelArestad/Press-This/pull/26

**Comment by MichaelArestad** [comment]
Heck yeah! Taking a look.

**Comment by MichaelArestad** [comment]
Looks good! Merged. I did spot something I want to change across the board. Going to modify the em function slightly.
