### ISSUE TITLE
Filter to disable the auto-embed magic

### ISSUE THREAD

**Issue by danielbachhuber** [MichaelArestad/Press-This#62]
For users that want to maintain the existing behavior of simply linking the equivalent of the `<title>` tag, it would be nice to be able to disable the auto-embed magic.

**Comment by stephdau** [comment]
Good idea, and easily doable. Ozz and I have discussed doing a full on
round on adding filters/action throughout, to make this version of PT more
extensible than its counterpart. We'll add that to the list. We've talked
about keeping that for the end though, once the software stabilizes (so,
close to or post merge).

**Comment by danielbachhuber** [comment]
> We've talked
> about keeping that for the end though, once the software stabilizes (so,
> close to or post merge).

Sounds good. Let me know if I can help with the audit.

**Comment by stephdau** [comment]
Added one in 7762edf.

Also added one to modif the PT data itself, in 0f353ef.
