### ISSUE TITLE
IE8 bugs list

### ISSUE THREAD

**Issue by MichaelArestad** [MichaelArestad/Press-This#66]
Did a quick test on IE8. Logged the issues I found.

- [ ] No placeholder text visible on the "Scan for URL" field
- [x] Can't add a title by clicking. (I'm guessing `pointer-events: none;` may not be supported. Tabbing works fine. Ish. (I can fix this)
- [x] Checkmarks don't show on selected list items in sidebar.
- [x] Bookmarklet code is too long. Limited to 2083 characters.CC @stephdau 
- [x] Scanning didn't appear to work when I tried.
- [x] Remove toggle in IE8 (easy for me to do)

**Comment by stephdau** [comment]
> Bookmarklet code is too long. Limited to 2083 characters.
We're at 3,945 chars at the moment, with newlines and spaces removed (as served in install screen). Frankly, I don't see that being halved, even by using techniques like uglification, etc. We might have to serve those users a simpler bookmarklet code. Our PT is fully backward compatible with the old bookmarklet code (though it prompts users to upgrade to the new one), so there's always that.

**Comment by stephdau** [comment]
Now serving older/shorter bookmarklet to MSIE < 9: 17531aa

**Comment by stephdau** [comment]
Fact that scanning did not appear to work seems to be because none of the JS seems to be. At 1st glance.

**Comment by stephdau** [comment]
JS no longer crashing on page load when scanning something, as of 2c3db2736c.

**Comment by marcelomazza** [comment]
> Can't add a title by clicking. (I'm guessing pointer-events: none; may not be supported. Tabbing works fine. Ish. (I can fix this)
Fixed in https://github.com/MichaelArestad/Press-This/pull/78

**Comment by MichaelArestad** [comment]
Fixed category checkmarks, border, and scroll issues.

![image](https://cloud.githubusercontent.com/assets/1123119/6312910/0d2e5f66-b94b-11e4-8a25-aeb045593544.png)

**Comment by MichaelArestad** [comment]
As far as the post formats, the `:checked` selector doesn't work in IE8. There's nothing I can do to just style the labels nicely. Will expose the radio buttons.

**Comment by MichaelArestad** [comment]
Fixed https://github.com/MichaelArestad/Press-This/commit/c04dca8b1cb43420608b673294c4a15cab9d9d0e

![image](https://cloud.githubusercontent.com/assets/1123119/6312920/25c51dac-b94c-11e4-9ead-a355b4dfef2e.png)

**Comment by MichaelArestad** [comment]
All, but the scan for URL. Opening issue just for that. Boom.
