### ISSUE TITLE
Thin white line in the left edge of the header (cross browser)

### ISSUE THREAD

**Issue by DrewAPicture** [MichaelArestad/Press-This#69]
Seeing what appears to be a very thin white border or margin on the left edge of the header. See attached for Firefox/Chrome (Mac) and IE (PC) screenshots.

![chrome_space](https://cloud.githubusercontent.com/assets/995399/6205287/91d7fca0-b526-11e4-88cf-c89c36a8f73e.png)
![firefox_space](https://cloud.githubusercontent.com/assets/995399/6205288/91d8e2e6-b526-11e4-8ba9-14c23c8a8d5e.png)
![ie_space](https://cloud.githubusercontent.com/assets/995399/6205286/91d76574-b526-11e4-877b-d0a31e2ef276.png)

**Comment by MichaelArestad** [comment]
Ha! Good catch. Leftover from the iframe days. Will fix.

**Comment by MichaelArestad** [comment]
Fixed. https://github.com/MichaelArestad/Press-This/commit/57eb951d83404b400a2dd13bfb9e4118a609322b
