### ISSUE TITLE
Submerged title field in Firefox

### ISSUE THREAD

**Issue by DrewAPicture** [MichaelArestad/Press-This#70]
When accessing press-this.php directly, it the Post title field in Firefox displays half-way submerged under the top of the editor, see attached. This also may happen with the bookmarklet window though I suspect this is related to the scenario only when the post title field is empty.

![firefox_title](https://cloud.githubusercontent.com/assets/995399/6205303/1c6b8c10-b527-11e4-8367-059b16de9110.png)

**Comment by MichaelArestad** [comment]
Fixed. https://github.com/MichaelArestad/Press-This/commit/486b4f3af75f831690d229fd5a9de245544bd877
