### ISSUE TITLE
Header styles don't match below the 320px break point

### ISSUE THREAD

**Issue by DrewAPicture** [MichaelArestad/Press-This#71]
It appears that in Firefox (at the very least) the header styles revert to white and blue below what I assume is about the 320px break point.

![screen shot 2015-02-16 at 5 53 42 pm](https://cloud.githubusercontent.com/assets/995399/6221756/255f988c-b605-11e4-8fac-1028bd15890d.png)

**Comment by stephdau** [comment]
Heh, nice...

@MichaelArestad : is [this](https://github.com/MichaelArestad/Press-This/blob/master/css/press-this.css#L1020) on purpose?

**Comment by MichaelArestad** [comment]
Yep. This is working as designed.

**Comment by MichaelArestad** [comment]
Changed https://github.com/MichaelArestad/Press-This/commit/52242a4606936b0b2692184e56e29187d303b465
