### ISSUE TITLE
A few security concerns

### ISSUE THREAD

**Issue by MichaelArestad** [MichaelArestad/Press-This#72]
@vortfu messaged me with a few security concerns

> Missing `current_user_can( 'edit_post', $post_id )` (or ... whatever) capability check in `WpPressThis::save()`
> https://github.com/MichaelArestad/Press-This/blob/master/press-this.php#L347
> ^ would allow anybody to create / update posts via the ajax endpoints (edited)

> The `msg` argument passed to `render_notice()` is being used unsafely (XSS)
https://github.com/MichaelArestad/Press-This/blob/master/js/app.js#L386
> e.g. http://vip.dev/wp-admin/press-this.php?u=https://%3Cscript%3Ealert(String.fromCharCode(161,32,116,111,100,97,32,115,117,32,98,97,115,101,32,101,115,32,112,101,114,116,101,110,101,99,101,32,97,32,110,111,115,111,116,114,111,115,32,33));%3C!--

> I haven't looked into it much, but I don't really trust `display_src` that much in `render_detected_media()` either

> https://github.com/MichaelArestad/Press-This/blob/master/js/app.js#L473
> https://github.com/MichaelArestad/Press-This/blob/master/js/app.js#L499

> and I'm not a fan of using `media_sideload_image()` or `download_url()` if they can be avoided (which they probably can't *shrug*)

CC @azaozz @stephdau

**Comment by stephdau** [comment]
Addressed in 6cc6c7d, cc1f153, and 297257c. `media_sideload_image()` and `download_url()` left untouched though, at least for now.
cc and props to @vortfu

**Comment by stephdau** [comment]
Closing for now. Please reopen if more concerns, or open a new issue.
