### ISSUE TITLE
Can't remove a tag from the tags box

### ISSUE THREAD

**Issue by MichaelArestad** [MichaelArestad/Press-This#76]
![image](https://cloud.githubusercontent.com/assets/1123119/6243093/30a57088-b6f8-11e4-9de6-4e5bc511caea.png)

**Comment by stephdau** [comment]
@iseulde or @azaozz : do you understand what `if ( e.which === 13 ) {` is ([ref](https://github.com/MichaelArestad/Press-This/blob/master/js/tag-box.js#L88)), and what it's for here?
In my test, when I click on a tag's x button, `e.which` comes in as 1, not 13, so the delete does not happen. Removing that `if` statement seems to fix the issue.

**Comment by azaozz** [comment]
`e.which` refers to "which" keyboard key was pressed, replaced by `e.keyCode`. Looking at that code, seems the removal of the tag elements is missing?

**Comment by stephdau** [comment]
Fixed in ca91cfb.

**Comment by stephdau** [comment]
For the record, that part isn't in the original tagBox, it was added to our copy in c923e11
