### ISSUE TITLE
Highlighted Excerpt fails if contains an ampersand

### ISSUE THREAD

**Issue by kraftbj** [MichaelArestad/Press-This#88]
The bookmarklet will fail to bring over the entire highlight if the selection includes an ampersand ( & ).

Duplication steps:
1. Visit http://www.brandonkraft.com/b/2015/02/paternity-leave/ (I was showing my wife PT after telling about the merge acceptance...)
2. Highlight the paragraph "Stay-at-home dad & part-time freelancer. Vanessa had two-weeks paid leave"
3. Click the bookmarklet
4. The excerpt brought in: "Stay-at-home dad"

**Comment by stephdau** [comment]
Fixed in 983f558. Bookmarklet was now using `encodeURI` instead of `encodeURIComponent`. Needs the latter. See http://stackoverflow.com/a/3608791/3207995
