### ISSUE TITLE
Add Category Parent select when adding a new category

### ISSUE THREAD

**Issue by MichaelArestad** [MichaelArestad/Press-This#91]
Ideally, we'll use `<li>` elements with proper attributes.

Working example: http://test.cita.illinois.edu/aria/radio/radio1.php

**Comment by marcelomazza** [comment]
Rough idea for this one:

![image](https://cloud.githubusercontent.com/assets/384622/6310929/263d0406-b95c-11e4-8e4c-89a6df7510d1.png)

What if we use the Category list that it's already there as "Parent selector". Yes, this can be odd being the same list, but maybe applying a good transition can work without being disorienting.

**Comment by MichaelArestad** [comment]
Done.
