### ISSUE TITLE
"Upgrade your bookmarklet" doesn't show the link

### ISSUE THREAD

**Issue by marcelomazza** [MichaelArestad/Press-This#95]
I'm on commit d1193830d60d54fd3e66b44f60adca2baf55a9d7 and there is no link showing up:

![image](https://cloud.githubusercontent.com/assets/384622/6311301/fe94d672-b960-11e4-9e60-f9fb71220785.png)

I tried to mess around with the code to see if I could bring it back but I couldn't. :(

Kind of related #31.

**Comment by MichaelArestad** [comment]
Looks fixed. :)
