### ISSUE TITLE
Suggested media and screen readers

### ISSUE THREAD

**Issue by afercia** [MichaelArestad/Press-This#99]
Posting here to keep track:
consider screen readers offer at least 3 different ways to read content: "Say All", (that is letting the screen reader read out all the content of a page), using down and up arrows to read step by step the content and using tab to read the focusable elements. With small variations, this is what NVDA reads out:
```
Press This! - Mozilla Firefox
Press This!  document
clickable <-- click event delegated on the body
clickable <-- click event delegated on the body

heading  level 1  My Beautiful Site

Show post options button

Post title
Post title heading  editable  level 2

list with 6 items
clickable <-- or just "space" if using arrows
clickable
clickable
clickable
clickable
clickable
out of list

application
Rich Text Area. Press Alt-Shift-H etc...
```

As you can see, the main issue here is about suggested media. They're just empty `<li>`s, nothing to read there. I'm not suggesting to have full meta data :) but at least some hint or some kind of text to be read out instead of "clickable". Maybe consider to use the media type? Video, Audio, Image, Tweet?

**Comment by stephdau** [comment]
Addressed. Will say "Suggested embed #[n]" or "Suggested image #[n]". Close issue at will, if okay.
